version: '3'
services: 
  chat:
    container_name: "websocket_chat"
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - redis
    ports:
      - 9090:9090
    volumes:
      - .:/app

  redis:
    container_name: "redis"
    image: "redis:latest"
    volumes:
      - "./docker/data/redis:/data"
    ports:
      - 6379:6379
